# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
  configurationVersion: 0.2.0
